#!/usr/bin/env bash

#####################################################
# Created by cryptopool.builders for crypto use...
# Creates the NGINX site for YiiMP, first with the self signed certificate and
# then, when requested, with a Let's Encrypt certificate.
#####################################################
source /etc/functions.sh
source /etc/multipool.conf
source "$STORAGE_ROOT/yiimp/.yiimp.conf"
PHP_VERSION="${PHP_VERSION:-${MULTIPOOL_DEFAULT_PHP_VERSION:-8.3}}"

if [[ "$wireguard" == "true" ]]; then
	source "$STORAGE_ROOT/yiimp/.wireguard.conf"
fi

# nginx 1.25.1+ deprecates "listen ... http2" in favour of "http2 on;".
NGINX_VERSION=$(nginx -v 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
if [ "$(printf '%s\n' "1.25.1" "${NGINX_VERSION:-0}" | sort -V | head -n 1)" == "1.25.1" ]; then
	NGINX_LISTEN_SSL=$'listen 443 ssl;\n\tlisten [::]:443 ssl;\n\thttp2 on;'
else
	NGINX_LISTEN_SSL=$'listen 443 ssl http2;\n\tlisten [::]:443 ssl http2;'
fi

# A plain domain is also served as www.<domain>.
if [[ "$UsingDomain" == "yes" && "$UsingSubDomain" != "yes" ]]; then
	NGINX_SERVER_NAMES="${DomainName} www.${DomainName}"
else
	NGINX_SERVER_NAMES="${DomainName}"
fi

# write_nginx_site self|letsencrypt
function write_nginx_site {
	local ssl_config conf
	if [ "$1" == "letsencrypt" ]; then
		ssl_config="ssl_certificate /etc/letsencrypt/live/${DomainName}/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/${DomainName}/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/${DomainName}/chain.pem;

	# HSTS (only with a certificate browsers trust)
	add_header Strict-Transport-Security \"max-age=31536000\" always;"
	else
		ssl_config="ssl_certificate ${STORAGE_ROOT}/ssl/ssl_certificate.pem;
	ssl_certificate_key ${STORAGE_ROOT}/ssl/ssl_private_key.pem;"
	fi

	conf=$(mktemp)
	cat > "$conf" <<EOF
#####################################################
# Source Generated by nginxconfig.io
# Updated by cryptopool.builders for crypto use...
#####################################################

# NGINX Simple DDoS Defense
limit_conn_zone \$binary_remote_addr zone=conn_limit_per_ip:10m;
limit_req_zone \$binary_remote_addr zone=req_limit_per_ip:40m rate=5r/s;
limit_conn conn_limit_per_ip 80;
limit_req zone=req_limit_per_ip burst=80 nodelay;

server {
	${NGINX_LISTEN_SSL}

	server_name ${NGINX_SERVER_NAMES};
	set \$base "/var/www/${DomainName}/html";
	root \$base/web;

	# SSL
	${ssl_config}

	# security
	include cryptopool.builders/security.conf;

	# logging
	access_log ${STORAGE_ROOT}/yiimp/site/log/${DomainName}.app.access.log;
	error_log ${STORAGE_ROOT}/yiimp/site/log/${DomainName}.app.error.log warn;

	# index.php
	index index.php;

	# index.php fallback
	location / {
		try_files \$uri \$uri/ /index.php?\$args;
	}
	location @rewrite {
		rewrite ^/(.*)\$ /index.php?r=\$1;
	}

	# handle .php
	location ~ \.php\$ {
		include cryptopool.builders/php_fastcgi.conf;
	}

	# additional config
	include cryptopool.builders/general.conf;
}

# HTTP redirect
server {
	listen 80;
	listen [::]:80;

	server_name .${DomainName};

	include cryptopool.builders/letsencrypt.conf;

	location / {
		return 301 https://${DomainName}\$request_uri;
	}
}
EOF
	sudo install -m 644 "$conf" "/etc/nginx/sites-available/${DomainName}.conf"
	rm -f "$conf"
}

echo -e " Creating the NGINX site for ${DomainName}...$COL_RESET"
write_nginx_site self
sudo ln -sfn "/etc/nginx/sites-available/${DomainName}.conf" "/etc/nginx/sites-enabled/${DomainName}.conf"
sudo mkdir -p "/var/www/${DomainName}/html"
sudo ln -sfn "$STORAGE_ROOT/yiimp/site/web" "/var/www/${DomainName}/html/web"
hide_output sudo nginx -t
restart_service nginx
restart_service "php${PHP_VERSION}-fpm"

if [[ "$InstallSSL" == "yes" ]]; then
	echo -e " Generating Certbot Request for ${DomainName} ...$COL_RESET"
	sudo mkdir -p /var/www/_letsencrypt
	sudo chown www-data /var/www/_letsencrypt
	CERTBOT_ARGS=(certonly --webroot -w /var/www/_letsencrypt -d "${DomainName}" -n --agree-tos --keep-until-expiring)
	if [[ "$SupportEmail" == *@localhost ]]; then
		CERTBOT_ARGS+=(--register-unsafely-without-email)
	else
		CERTBOT_ARGS+=(-m "$SupportEmail")
	fi
	# Certbot is allowed to fail (e.g. DNS not updated yet): keep the self
	# signed certificate in that case.
	sudo certbot "${CERTBOT_ARGS[@]}" > /dev/null 2>&1 || true
	if sudo test -f "/etc/letsencrypt/live/${DomainName}/fullchain.pem"; then
		# Reload NGINX after a successful renewal (the Ubuntu certbot package
		# renews certificates from a systemd timer).
		sudo mkdir -p /etc/letsencrypt/renewal-hooks/deploy/
		printf '#!/bin/sh\nnginx -t && systemctl reload nginx\n' \
			| sudo tee /etc/letsencrypt/renewal-hooks/deploy/nginx-reload.sh > /dev/null
		sudo chmod 755 /etc/letsencrypt/renewal-hooks/deploy/nginx-reload.sh
		# I am SSL Man!
		write_nginx_site letsencrypt
		hide_output sudo nginx -t
		restart_service nginx
		restart_service "php${PHP_VERSION}-fpm"
	else
		echo -e "Certbot generation failed, after the installer is finished check /var/log/letsencrypt (must be root to view) on why it failed."
	fi
fi

cd "$HOME/multipool/yiimp_single" || exit 1
