#!/usr/bin/env bash
#
#    10-sysinfo - generate the system information
#    Copyright (c) 2013 Nick Charlton
#
#    Authors: Nick Charlton <hello@nickcharlton.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#####################################################
# Updated by cryptopool.builders for crypto use...
#####################################################

# shellcheck disable=SC1091
[ -r /etc/multipool.conf ] && source /etc/multipool.conf
STORAGE_ROOT=${STORAGE_ROOT:-/home/crypto-data}

date=$(date)

# screen_status PATTERN: "running" if a process matching PATTERN exists.
screen_status() {
	if pgrep -f -- "$1" > /dev/null 2>&1; then
		echo "running"
	else
		echo "stopped"
	fi
}
main=$(screen_status "crons/main.sh")
blocks=$(screen_status "crons/blocks.sh")
loop2=$(screen_status "crons/loop2.sh")
debug=$(screen_status "log/debug.log")
daemon="$STORAGE_ROOT/wallets"
site="$STORAGE_ROOT/yiimp/site"
hint1="To view a screen type, screen -r main|loop2|blocks|debug"
hint2="To detach from a screen type, ctrl+a+d"
divider="=============================="
divider=$divider$divider
header=" %-7s %-25s %-16s %-15s\n"
width=50
RED=$'\033[00;31m'
GREEN=$'\033[00;32m'
RESTORE=$'\033[0m'

# status_color STATUS: STATUS in red (stopped) or green (running).
status_color() {
	if [[ "$1" == "stopped" ]]; then
		echo "${RED}$1${RESTORE}"
	else
		echo "${GREEN}$1${RESTORE}"
	fi
}
echo "System information as of: $date"
echo
[ -x /usr/bin/landscape-sysinfo ] && /usr/bin/landscape-sysinfo
echo
echo "YiiMP Information:"
printf "%$width.${width}s\n" "$divider"
# shellcheck disable=SC2059 # $header is the format string
printf "$header" "Main:" "$(status_color "$main")" "Daemon Directory:" "$daemon"
# shellcheck disable=SC2059
printf "$header" "Blocks:" "$(status_color "$blocks")" "YiiMP Directory:" "$site"
# shellcheck disable=SC2059
printf "$header" "Loop2:" "$(status_color "$loop2")" "Hint: $hint1"
# shellcheck disable=SC2059
printf "$header" "Debug:" "$(status_color "$debug")" "Hint: $hint2"
echo
echo "To start|stop|restart a screen use the following command..."
echo "screens start|stop|restart main|loop2|blocks|debug"
echo
echo "To reload this MOTD just type motd..."
echo
echo "Donations for continued support of this script are welcomed at:"
echo
echo "BTC 3DvcaPT3Kio8Hgyw4ZA9y1feNnKZjH7Y21"
echo "BCH qrf2fhk2pfka5k649826z4683tuqehaq2sc65nfz3e"
echo "ETH 0x6A047e5410f433FDBF32D7fb118B6246E3b7C136"
echo "LTC MLS5pfgb7QMqBm3pmBvuJ7eRCRgwLV25Nz"
echo
[ -x /usr/lib/update-notifier/update-motd-reboot-required ] && /usr/lib/update-notifier/update-motd-reboot-required
[ -x /usr/lib/update-notifier/apt-check ] && /usr/lib/update-notifier/apt-check --human-readable
echo
