#!/usr/bin/env bash
#####################################################
# Source code from https://codereview.stackexchange.com/questions/55077/small-bash-script-to-start-and-stop-named-services
# Updated by cryptopool.builders for crypto use...
#####################################################
# Usage: screens start|stop|restart main|loop2|blocks|debug ...

source /etc/multipool.conf
source "$STORAGE_ROOT/yiimp/.prescreens.start.conf"

start_screen() {
	case $1 in
		main) screen -dmS main bash "${CRONS}/main.sh" ;;
		loop2) screen -dmS loop2 bash "${CRONS}/loop2.sh" ;;
		blocks) screen -dmS blocks bash "${CRONS}/blocks.sh" ;;
		debug) screen -dmS debug tail -F "${LOG_DIR}/debug.log" ;;
	esac
}

stop_screen() {
	screen -X -S "$1" quit
}

startstop_screen() {
	local cmd=$1 name=$2
	case $cmd in
		stop) stop_screen "$name" ;;
		start) start_screen "$name" ;;
		restart)
			stop_screen "$name"
			sleep 1
			start_screen "$name"
			;;
	esac
}

startstop_service() {
	local cmd=$1 name=$2
	sudo systemctl "$cmd" "$name"
}

case "$1" in
	start|stop|restart) cmd=$1 ;;
	*)
		echo "usage: $0 [start|stop|restart] main|loop2|blocks|debug"
		exit 1
		;;
esac
shift

for name; do
	case "$name" in
		main|loop2|blocks|debug) startstop_screen "$cmd" "$name" ;;
		*) startstop_service "$cmd" "$name" ;;
	esac
done
